table Customers
	lineageTag: 527e59e3-a8b8-4574-bff7-081180fbace0

	column customer_id
		dataType: string
		lineageTag: ad039d7b-08b5-486d-856d-759ac990f57e
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_unique_id
		dataType: string
		lineageTag: 401ac807-f0ee-4052-b29d-2fe8e860f82d
		summarizeBy: none
		sourceColumn: customer_unique_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: 6c73db0b-4f6d-4b4d-af7d-200796281dee
		summarizeBy: none
		sourceColumn: customer_zip_code_prefix

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 965e4aff-c69a-4ee5-a6d4-4c83d0009b91
		summarizeBy: none
		sourceColumn: customer_city

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 7dd2d1bb-07d6-4028-bc78-4d62a8791ccf
		summarizeBy: none
		sourceColumn: customer_state

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Sangram Bharat\OneDrive\personal\Project Portfolio\Brazilian E-Commerce Analysis (Olist)\olist_customers_dataset.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_unique_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

