table Orders
	lineageTag: b3e14436-af1b-4b62-b8ff-aefd852cd157

	column order_id
		dataType: string
		lineageTag: 4ec21259-bcf2-4e78-8666-6fc768d34728
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		lineageTag: e537f601-40fb-438c-aa2f-114c4a855d6a
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: c31298b1-1027-4808-afce-b97f181332fc
		summarizeBy: none
		sourceColumn: order_status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Is_Delivered
		dataType: int64
		formatString: 0
		lineageTag: af99b70e-bb8c-49d3-b668-3b323be899c9
		summarizeBy: sum
		sourceColumn: Is_Delivered

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_purchase_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: b6fbe6e8-1929-4b4e-afa6-d7f152e130c7
		summarizeBy: none
		sourceColumn: order_purchase_timestamp

		variation Variation
			isDefault
			relationship: 2160b0f1-7a4f-4f46-9179-3120740aff8a
			defaultHierarchy: LocalDateTable_e0fb3646-a0a2-4337-bd70-4127471bd4ef.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_approved_at
		dataType: dateTime
		formatString: General Date
		lineageTag: c873e463-8254-4989-9fc3-8aebfdae11ca
		summarizeBy: none
		sourceColumn: order_approved_at

		variation Variation
			isDefault
			relationship: d3d74276-4712-430b-949b-0e5de3521c01
			defaultHierarchy: LocalDateTable_7bbabcbc-e49f-4e67-85ac-ab59432c25da.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_delivered_carrier_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 22aa2657-2282-4451-9776-4573511fce9a
		summarizeBy: none
		sourceColumn: order_delivered_carrier_date

		variation Variation
			isDefault
			relationship: 0b1aa408-ad49-444d-b1a9-f028ccbe2acc
			defaultHierarchy: LocalDateTable_43cde287-9dfd-48e2-bfc1-fbff95d90c31.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_delivered_customer_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 1e2d2bd9-5231-4fcc-8fc4-00a77f9209d2
		summarizeBy: none
		sourceColumn: order_delivered_customer_date

		variation Variation
			isDefault
			relationship: fa1c3f85-cc5a-42a3-a95a-224a60bcdddd
			defaultHierarchy: LocalDateTable_7fa30440-ec41-4b4d-9091-c9cad476c179.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_estimated_delivery_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 9fccf1aa-7dec-4bdc-81b8-01882c5e234f
		summarizeBy: none
		sourceColumn: order_estimated_delivery_date

		variation Variation
			isDefault
			relationship: 02a81730-b2a0-4c0b-9fa3-b105ca3daeec
			defaultHierarchy: LocalDateTable_37aef842-3ddb-4292-801c-54355f73778a.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 74c119b3-7ecf-41fd-8c90-c68ca9e8d082
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivery days' = DATEDIFF(Orders[order_purchase_timestamp],Orders[order_delivered_customer_date],DAY)
		formatString: 0
		lineageTag: b37a85b4-bc8c-419b-affd-c4d2de036b2a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Customer_state
		dataType: string
		lineageTag: 8e31e694-18fa-4fe1-8ee0-0185e1098fc8
		summarizeBy: none
		sourceColumn: Customer_state

		annotation SummarizationSetBy = Automatic

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Sangram Bharat\OneDrive\personal\Project Portfolio\Brazilian E-Commerce Analysis (Olist)\olist_orders_dataset.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_purchase_timestamp", type datetime}, {"order_approved_at", type datetime}, {"order_delivered_carrier_date", type datetime}, {"order_delivered_customer_date", type datetime}, {"order_estimated_delivery_date", type datetime}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Is_Delivered", each if [order_status] = "delivered" then 1 else 0),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"order_id", "customer_id", "order_status", "Is_Delivered", "order_purchase_timestamp", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Reordered Columns",{{"Is_Delivered", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Order Date", each Date.From([order_purchase_timestamp])),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom1",{"order_id", "customer_id", "order_status", "Is_Delivered", "order_purchase_timestamp", "Order Date", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns1", {"customer_id"}, Customers, {"customer_id"}, "Customers", JoinKind.LeftOuter),
				    #"Expanded Customers" = Table.ExpandTableColumn(#"Merged Queries", "Customers", {"customer_state"}, {"Customers.customer_state"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Customers",{{"Customers.customer_state", "Customer_state"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

